# Generated by Django 3.1 on 2020-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('default', 'Default'), ('google', 'Google'), ('kakao', 'Kakao')], default='default', max_length=50),
        ),
    ]
