# Generated by Django 3.0.8 on 2020-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20200804_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='coverImage',
            field=models.ImageField(blank=True, upload_to='coverimage'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='music'),
        ),
    ]
